# Generated by Django 5.2.7 on 2026-01-09 15:29

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_caretaker_specialisation_alter_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CaretakerCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='caretakers/cvs/', validators=[accounts.validators.validate_file_type_and_size])),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('caretaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='accounts.caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='caretakers/diplomas/', validators=[accounts.validators.validate_file_type_and_size])),
                ('diploma_type', models.CharField(choices=[('DEGREE', 'Degree'), ('CERTIFICATE', 'Certificate'), ('LICENSE', 'License')], max_length=20)),
                ('year_acquired', models.PositiveIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='accounts.caretaker')),
            ],
        ),
    ]
