# Generated by Django 5.2.7 on 2026-01-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_caretaker_is_approved_caretaker_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretaker',
            old_name='user_image_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='academic_title',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='specialisation',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='working_since',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='year_acquired',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='grad_year',
            field=models.PositiveIntegerField(blank=True, help_text='The year in which the person graduated as a psychologist.', null=True),
        ),
    ]
