# Generated by Django 5.2.7 on 2026-01-10 20:59

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_user_image_url_caretaker_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='diploma_type',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='caretakers/images/', validators=[accounts.validators.validate_file_type_and_size]),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='image_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='caretakers/certificates/', validators=[accounts.validators.validate_file_type_and_size])),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.caretaker')),
            ],
        ),
    ]
