# Generated by Django 5.2.7 on 2026-01-14 20:08

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_caretaker_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='caretakers/images/', validators=[accounts.validators.validate_caretaker_image]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('caretaker', 'Caretaker'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
