# Generated by Django 5.2.7 on 2026-01-16 18:53

import accounts.upload_paths
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_google_sub_alter_caretaker_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.upload_paths.caretaker_image_upload_to, validators=[accounts.validators.validate_caretaker_image]),
        ),
        migrations.AlterField(
            model_name='caretakercv',
            name='file',
            field=models.FileField(upload_to=accounts.upload_paths.cv_upload_to, validators=[accounts.validators.validate_file_type_and_size]),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='file',
            field=models.FileField(upload_to=accounts.upload_paths.diploma_upload_to, validators=[accounts.validators.validate_file_type_and_size]),
        ),
    ]
