# Generated by Codex for production-safe phone length handling.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_helpcategory_assistant_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caretaker",
            name="tel_num",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
