# Generated by Django 5.2.7 on 2026-01-12 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_user_google_sub_alter_caretaker_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_start', models.DateTimeField()),
                ('requested_end', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_category', models.CharField(blank=True, max_length=100, null=True)),
                ('crisis_flag', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='accounts.caretaker')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_requests', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('confirmed_pending_sync', 'Confirmed (pending sync)'), ('confirmed', 'Confirmed'), ('confirmed_sync_failed', 'Confirmed (sync failed)'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed_pending_sync', max_length=30)),
                ('external_event_id', models.CharField(blank=True, max_length=200, null=True)),
                ('calendar_id', models.CharField(blank=True, max_length=200, null=True)),
                ('conference_link', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.caretaker')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.student')),
                ('appointment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointments.appointmentrequest')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60)),
                ('recurrence_rule', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.caretaker')),
            ],
            options={
                'ordering': ['caretaker', 'start'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_logs', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['caretaker', 'status'], name='appointment_caretak_8231a2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['student', 'status'], name='appointment_student_136758_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['caretaker', 'start'], name='appointment_caretak_877838_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['external_event_id'], name='appointment_externa_ecb6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['caretaker', 'start'], name='appointment_caretak_7c05da_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['caretaker', 'end'], name='appointment_caretak_ed2211_idx'),
        ),
    ]
