# Generated by Django 5.2.7 on 2026-01-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_google_sub_alter_caretaker_image_and_more'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='accounts.caretaker')),
            ],
            options={
                'ordering': ['caretaker', 'start'],
                'indexes': [models.Index(fields=['caretaker', 'start'], name='appointment_caretak_1f6fc7_idx')],
                'unique_together': {('caretaker', 'start')},
            },
        ),
    ]
