# Generated by Django 5.2.7 on 2026-01-14 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_google_sub_alter_caretaker_image_and_more'),
        ('appointments', '0002_availabilityslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('consumed', 'Consumed')], default='active', max_length=20)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='accounts.caretaker')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['caretaker', 'start'], name='appointment_caretak_18673b_idx'), models.Index(fields=['status'], name='appointment_status_679082_idx')],
            },
        ),
    ]
