# Generated by Django 5.2.7 on 2026-02-26 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_caretaker_image_alter_caretakercv_file_and_more'),
        ('appointments', '0003_reservationhold'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='appointments.appointment')),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to='accounts.caretaker')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_feedbacks', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['caretaker', 'created_at'], name='appointment_caretak_60a5f6_idx'), models.Index(fields=['is_public'], name='appointment_is_publ_db4e78_idx')],
            },
        ),
    ]
