# Generated by Django 5.2.7 on 2026-03-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointmentfeedback"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="appointmentfeedback",
            new_name="appointment_caretak_ff1e17_idx",
            old_name="appointmen_caretak_b164c0_idx",
        ),
        migrations.RenameIndex(
            model_name="appointmentfeedback",
            new_name="appointment_student_768540_idx",
            old_name="appointmen_student_3c1772_idx",
        ),
    ]
