# Generated by Django 5.2.7 on 2026-04-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0005_rename_appointmen_caretak_b164c0_idx_appointment_caretak_ff1e17_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentrequest",
            name="ai_transcript_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="ai_transcript_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
