# Generated by Django 5.2.7 on 2026-01-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_journalentry_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
