# Generated by Django 5.2.7 on 2026-04-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_alter_journalentry_mood"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="crisis_detected",
            field=models.BooleanField(default=False),
        ),
    ]
