"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from pathlib import Path
from datetime import timedelta
from urllib.parse import urlparse

import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.environ.get(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


def unique(values: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            result.append(value)
    return result


def is_unsafe_secret_key(value: str) -> bool:
    stripped = value.strip()
    return (
        not stripped
        or stripped in {"dev-secret-key", "change-me"}
        or stripped.startswith("django-insecure-")
        or len(set(stripped)) < 5
        or len(stripped) < 32
    )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
APP_ENV = os.environ.get("APP_ENV", "development").strip().lower()
DEBUG = env_bool("DEBUG", APP_ENV not in {"production", "staging", "preview"})
IS_PRODUCTION = APP_ENV in {"production", "staging", "preview"} or not DEBUG

SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")
if IS_PRODUCTION and is_unsafe_secret_key(SECRET_KEY):
    raise ImproperlyConfigured(
        "Production requires a strong SECRET_KEY provided through the environment."
    )

# Registration token TTL (seconds) for stateless JWT used during signup
REGISTRATION_TOKEN_EXP_SECONDS = int(os.environ.get("REGISTRATION_TOKEN_EXP_SECONDS", 7200))

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
AI_CONVERSATION_MODEL = os.environ.get("AI_CONVERSATION_MODEL", "gpt-5.2-chat-latest")
AI_STRUCTURED_MODEL = os.environ.get("AI_STRUCTURED_MODEL", "gpt-5.2")
AI_CONVERSATION_TIMEOUT_SEC = float(os.environ.get("AI_CONVERSATION_TIMEOUT_SEC", "12"))
AI_CONVERSATION_MAX_ATTEMPTS = int(os.environ.get("AI_CONVERSATION_MAX_ATTEMPTS", "2"))
AI_BACKUP_CONVERSATION_MODEL = os.environ.get("AI_BACKUP_CONVERSATION_MODEL", "gpt-4o-mini")
AI_BACKUP_CONVERSATION_TIMEOUT_SEC = float(os.environ.get("AI_BACKUP_CONVERSATION_TIMEOUT_SEC", "8"))
AI_MAX_PREVIOUS_SUMMARIES = int(os.environ.get("AI_MAX_PREVIOUS_SUMMARIES", "2"))
AI_MAX_RECENT_CHAT_MESSAGES = int(os.environ.get("AI_MAX_RECENT_CHAT_MESSAGES", "8"))

DEFAULT_ALLOWED_HOSTS = [
    ".railway.app",
    "programsko-inzenjerstvo-production-9d1d4up.railway.app",
    "localhost",
    "127.0.0.1",
]
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", DEFAULT_ALLOWED_HOSTS)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
EMAIL_PROVIDER = os.environ.get('EMAIL_PROVIDER', '')
RESEND_API_KEY = os.environ.get('RESEND_API_KEY')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'storages',
    'accounts',
    'users',
    'journal',
    'calendar_integration',
    'assistant',
    'appointments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",

    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'accounts.authentication.CookieJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema'
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CareFree API',
    'DESCRIPTION': 'Django REST API za aplikaciju CareFree',
    'VERSION': '1.0.0-alpha',
}


# Django project settings.py

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_CREDENTIALS = True
DEFAULT_CORS_ALLOWED_ORIGINS = [
    "https://programsko-inzenjerstvo.vercel.app",
    "https://programsko-inzenjerstvo-production-9d1d4up.railway.app",
    "http://localhost:3000",
    "http://localhost:3001",
]
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", DEFAULT_CORS_ALLOWED_ORIGINS)

DEFAULT_CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://programsko-inzenjerstvo.*\.vercel\.app$",
]
CORS_ALLOWED_ORIGIN_REGEXES = env_list(
    "CORS_ALLOWED_ORIGIN_REGEXES", DEFAULT_CORS_ALLOWED_ORIGIN_REGEXES
)

DEFAULT_CSRF_TRUSTED_ORIGINS = [
    "https://programsko-inzenjerstvo.vercel.app",
    "https://*.railway.app",
]
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", DEFAULT_CSRF_TRUSTED_ORIGINS)

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3001")
EMAIL_ASSETS_BASE_URL = os.environ.get("EMAIL_ASSETS_BASE_URL", "").strip()

frontend_host = urlparse(FRONTEND_URL).hostname
if frontend_host and frontend_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = unique([*ALLOWED_HOSTS, frontend_host])
if FRONTEND_URL.startswith(("http://", "https://")) and FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = unique([*CORS_ALLOWED_ORIGINS, FRONTEND_URL])
if FRONTEND_URL.startswith(("http://", "https://")) and FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = unique([*CSRF_TRUSTED_ORIGINS, FRONTEND_URL])

SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", IS_PRODUCTION)
SESSION_COOKIE_SAMESITE = os.environ.get(
    "SESSION_COOKIE_SAMESITE", "None" if IS_PRODUCTION else "Lax"
)
CSRF_COOKIE_SAMESITE = os.environ.get(
    "CSRF_COOKIE_SAMESITE", "None" if IS_PRODUCTION else "Lax"
)
SESSION_COOKIE_DOMAIN = os.environ.get("SESSION_COOKIE_DOMAIN") or None
CSRF_COOKIE_DOMAIN = os.environ.get("CSRF_COOKIE_DOMAIN") or None

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", IS_PRODUCTION)
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if env_bool("USE_X_FORWARDED_PROTO", IS_PRODUCTION)
    else None
)
USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", IS_PRODUCTION)
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000" if IS_PRODUCTION else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", IS_PRODUCTION)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool("SECURE_CONTENT_TYPE_NOSNIFF", True)
SECURE_REFERRER_POLICY = os.environ.get("SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin")

#Google service account settings for Calendar API (server-to-server)
GOOGLE_SERVICE_ACCOUNT_JSON = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON")
GOOGLE_SERVICE_ACCOUNT_FILE = os.environ.get("GOOGLE_SERVICE_ACCOUNT_FILE")
if GOOGLE_SERVICE_ACCOUNT_JSON:
    try:
        import json, base64
        GOOGLE_SERVICE_ACCOUNT_INFO = json.loads(base64.b64decode(GOOGLE_SERVICE_ACCOUNT_JSON))
    except Exception:
        GOOGLE_SERVICE_ACCOUNT_INFO = None
else:
    GOOGLE_SERVICE_ACCOUNT_INFO = None

GOOGLE_CALENDAR_ID = os.environ.get("GOOGLE_CALENDAR_ID", "").strip()
ENABLE_USER_GOOGLE_CALENDAR_SYNC = os.environ.get("ENABLE_USER_GOOGLE_CALENDAR_SYNC", "False") == "True"

# Google OAuth settings for per-user calendar access
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET")
GOOGLE_OAUTH_REDIRECT_URI = os.environ.get("GOOGLE_OAUTH_REDIRECT_URI")
GOOGLE_SHARED_CALENDAR_ACCOUNT_EMAIL = os.environ.get("GOOGLE_SHARED_CALENDAR_ACCOUNT_EMAIL", "").strip()

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')

#Blackblaze B2 Cloud Storage
AWS_ACCESS_KEY_ID = os.getenv("B2_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("B2_APPLICATION_KEY")

AWS_STORAGE_BUCKET_NAME = os.getenv("B2_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = os.getenv("B2_ENDPOINT")
AWS_S3_REGION_NAME = os.getenv("B2_REGION")

AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = True
AWS_S3_FILE_OVERWRITE = False
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "path"

USE_CLOUD_MEDIA = os.getenv("USE_CLOUD_MEDIA", "False" if DEBUG else "True") == "True"

if USE_CLOUD_MEDIA and AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME and AWS_S3_ENDPOINT_URL:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
# Development convenience: when DEBUG=True run Celery tasks eagerly (synchronously)
# so you don't need a broker/worker for local development. This executes tasks
# immediately in-process when you call `.delay()` or `.apply_async()`.
# IMPORTANT: This is only for local/dev use. For staging/production use a real
# broker (Redis/RabbitMQ) and workers.
if DEBUG:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES_EXCEPTIONS = True

#enkripcija: ključ za enkripciju na strani servera (Fernet base64 ključ)
#u produkciji će trebati postaviti `ENCRYPTION_KEY` env var na base64 urlsafe kljuc (32 url-safe bajta enkodirana)
try:
    from cryptography.fernet import Fernet
except Exception:
    Fernet = None

ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY')
if not ENCRYPTION_KEY:
    #samo za razvoj: generiramo privremeni ključ ako nije postavljen
    if DEBUG and Fernet is not None:
        import warnings
        warnings.warn("ENCRYPTION_KEY not set — generating temporary key for DEBUG mode. Do NOT use in production.")
        ENCRYPTION_KEY = Fernet.generate_key().decode()
    else:
        ENCRYPTION_KEY = None

if IS_PRODUCTION and not ENCRYPTION_KEY:
    raise ImproperlyConfigured(
        "Production requires ENCRYPTION_KEY so encrypted journal data remains readable across restarts."
    )
