# Generated by Django 5.2.7 on 2025-12-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("calendar_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("google_event_id", models.CharField(max_length=255, unique=True)),
                ("summary", models.CharField(blank=True, max_length=512)),
                ("description", models.TextField(blank=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("meet_link", models.URLField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(blank=True, max_length=100, null=True)),
                ("source_id", models.CharField(blank=True, max_length=100, null=True)),
                ("calendar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="calendar_integration.calendar")),
            ],
        ),
    ]
