# Generated by Django 5.2.7 on 2026-01-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='summary',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
