# Generated by Django 5.2.7 on 2026-01-14 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0002_alter_calendarevent_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconcileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(help_text='missing_locally|missing_in_google|changed', max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_integration.calendar')),
            ],
        ),
    ]
