# Generated by Django 5.2.7 on 2026-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0003_reconcilelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemGoogleCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="shared_calendar", max_length=100, unique=True
                    ),
                ),
                (
                    "google_account_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_uri", models.CharField(blank=True, max_length=255, null=True)),
                ("client_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("scopes", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
