# Generated by Codex on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantsession",
            name="closure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("support", "Support"),
                    ("recommendation", "Recommendation"),
                    ("crisis", "Crisis"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assistantsession",
            name="danger_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assistantsession",
            name="main_category",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="assistantsession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("support", "Support"),
                    ("recommendation", "Recommendation"),
                    ("crisis", "Crisis"),
                ],
                default="support",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="assistantsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("recommendation_offered", "Recommendation Offered"),
                    ("recommendation_ready", "Recommendation Ready"),
                    ("support_completed", "Support Completed"),
                    ("recommendation_completed", "Recommendation Completed"),
                    ("crisis_active", "Crisis Active"),
                    ("ended_manual", "Ended Manually"),
                ],
                default="active",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="assistantsession",
            name="subcategories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assistantsessionsummary",
            name="include_in_context",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="assistantsessionsummary",
            name="main_category",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="assistantsessionsummary",
            name="recommended_caretaker_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assistantsessionsummary",
            name="subcategories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assistantsessionsummary",
            name="summary_type",
            field=models.CharField(
                choices=[
                    ("support", "Support"),
                    ("recommendation", "Recommendation"),
                    ("crisis", "Crisis"),
                ],
                default="support",
                max_length=20,
            ),
        ),
    ]
